name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Miniforge3
          miniforge-version: latest
          python-version: 3.10
          activate-environment: testenv
          environment-file: environment.yml
          auto-activate-base: false

      - name: Verify Conda Environment
        shell: bash -l {0}
        run: |
          echo "[conda info]"
          conda info
          echo "[conda list]"
          conda list
          echo "[which python]"
          which python
          echo "[python version]"
          python --version

      - name: Optional: Import check for critical packages
        shell: bash -l {0}
        run: |
          python -c "import numpy"  # replace or expand with actual dependencies

      - name: Install flake8 and pytest
        shell: bash -l {0}
        run: |
          conda install flake8 pytest

      - name: Lint with flake8
        shell: bash -l {0}
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        shell: bash -l {0}
        run: |
          pytest
